db:
    # image: postgres
    image: forum_db

redis:
    # redis server
    image: redis

web:
    # build: .
    image: myapp
    # command: bash -c "python manage.py makemigrations && python manage.py migrate && uwsgi --http :8000 --module forum.wsgi"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    links:
        - db
        - redis
