# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10 on 2017-09-07 05:35
=======
# Generated by Django 1.10 on 2017-07-01 04:01
>>>>>>> 64138a715f2eba0b385bb60ada4b19b3625355bc
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('block', '0003_auto_20170907_1154'),
=======
        ('block', '0001_initial'),
>>>>>>> 64138a715f2eba0b385bb60ada4b19b3625355bc
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='文章名称')),
<<<<<<< HEAD
                ('content', models.CharField(max_length=20, verbose_name='文章描述')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '删除')], verbose_name='状态')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新时间')),
=======
                ('content', models.CharField(max_length=1000, verbose_name='文章描述')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '删除')], verbose_name='状态')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_timestamp', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
>>>>>>> 64138a715f2eba0b385bb60ada4b19b3625355bc
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block', verbose_name='所属版块')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
            },
        ),
    ]
