# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='文章作者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block', verbose_name='所属版块'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='文章描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='文章名称'),
        ),
    ]
